---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: svm-latex-syllabus.tex
geometry: margin=1in

title: "Biology 364/664: Analysis and Visualization of Biological Data"
author: Prof. Ken Field
date: "Spring 2019"

email: "kfield@bucknell.edu"
web: "https://github.com/KField-Bucknell"
officehours: "T 12:00-1:00 pm"
office: "208 Biology Building"
classroom: "TBA"
classhours: "TR 11:00-11:52 am, T 1:00-5:00 pm"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2019-01-14")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}

```

# Course Description

Introduction to the process of data exploration and visualization using state-of-the-art computational techniques. Using “big data” from public archives or their own research projects, students will learn how to rigorously analyze and visualize complex biological datasets. Lab will include hands-on work with R and virtual reality. No programming experience required.

# Course Objectives

1. Using R, students will analyze, visualize, and intepret real-world datasets.

2. Students will learn to apply rigorous standards to experimental design and interpretation.

3. Working as a team, students will complete novel projects utilizing whole-transcriptome or whole-genome datasets.

4. Students will present their final projects using complex multi-dimensional data visualizations.

# Required Readings


# Course Policy

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff. Don't be that guy.

## Grading Policy

- **20%** of your grade will be determined by a midterm during normal class hours.

- **20%** of your grade will be determined by a term paper that documents your appreciation of Foghat's "Slow Ride", the most important song ever written. "Slow Ride" is what Mozart wishes *Don Giovanni* could have been.

- **10%** of your grade will be determined by your attendance and participation in class. Generally, ask questions and answer them.

- **20%** of your grade will be determined by a 20-page term paper on when exactly "The Love Boat" jumped the proverbial shark. You will address whether this shark-jumping can be attributed to Ted McGinley, the introduction of Jill Whelan as "Vicki", or some other cause.

- **30%** of your grade will be determined by a final exam.

## Attendance Policy



## E-mail Policy


## Make-Up Exam Policy

There are **NO** make-ups for missed exams. Don't bother asking.

## Academic Dishonesty Policy

Don’t cheat. Don’t be that guy. Yes, you. You know exactly what I’m talking about too.

## Disabilities Policy

Federal law mandates the provision of services at the university-level to qualified students with disabilities. Make sure to include all that relevant information here.


\newpage

# Class Schedule

Students must read the following before Tuesday's class session.  Important: class readings are subject to change, contingent on mitigating circumstances and the progress we make as a class.  Students are encouraged to attend lectures and check the course website for updates. 

## `r advdate(mon, 1)`: Syllabus Day

*No class Thursday (Political scientists usually have a conference to start the semester).*

Read *all* associated documents on course website.
  
  - [Taking Good Notes](http://svmiller.com/blog/2014/09/taking-good-notes/)
  - [Dos and Dont's of Writing for Students](http://svmiller.com/blog/2015/06/dos-and-donts-of-writing-for-students/)
  - [Assorted Tips for Students on Writing Research Papers](http://svmiller.com/blog/2015/12/assorted-tips-students-research-papers/)
  - [Exam Grading Policy](https://www.dropbox.com/s/apihjs7di81aqcv/svm-exam-grading-policy.pdf?dl=0)
  - [Fun with Attendance and Grades (i.e. Students Should Attend Class)](http://svmiller.com/blog/2016/05/fun-with-attendance-grades/)
    

## `r advdate(mon, 2)`: The First Topic Where We Read John Vasquez


##  `r advdate(mon, 3)`: Read the Nos. 90-97 Items in My Bib



*Your "Slow Ride" appreciation paper is due in Thursday's class*.

##  `r advdate(mon, 4)`: Read Bib Item No. 120


##  `r advdate(mon, 5)`: The Fourth Topic with Bib Item No. 510



##  `r advdate(mon, 6)`: Keep
##  `r advdate(mon, 7)`: Going
##  `r advdate(mon, 8)`: Down

##  `r advdate(mon, 9)`: the

##  `r advdate(mon, 10)`: Line

##  `r advdate(mon, 11)`: Until

##  `r advdate(mon, 12)`: You

## `r advdate(mon, 13)`: Are

##  `r advdate(mon, 14)`: Done

##  `r advdate(mon, 15)`: with


##  `r advdate(mon, 16)`: your


##  `r advdate(mon, 17)`: Syllabus 
