---
title: "PCA.Temple.forVR"
author: "Ken Field"
date: "4/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(stringr)
library(RColorBrewer)
library(cowplot)
```

## Loading and cleaning Data

```{r}
warmPd_posvswarmPd_neg_complete <- read_delim("../04-Data/warmPd-posvswarmPd-neg.complete.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
genetable <- warmPd_posvswarmPd_neg_complete %>% 
  select(starts_with("norm.")) %>%
  filter(complete.cases(.))

head(genetable)
colnames(genetable) <- gsub("norm.","", colnames(genetable))

genematrix1 <- warmPd_posvswarmPd_neg_complete %>% 
  select(c(Id,starts_with("norm."))) %>%
  filter(complete.cases(.))

genematrix <- as.matrix(genematrix1[,2:23])
rownames(genematrix) <- genematrix1$Id
head(genematrix)

colnames(genematrix) <- gsub("norm.","", colnames(genematrix))
```

## PCA

```{r}
pc <- prcomp(t(log2(genematrix+0.01)), center = TRUE, scale. = TRUE)

names(pc)
pcagroup <- as.factor(str_sub(colnames(genematrix), start=-9))
pcagroup
pcanames <- as.character(str_sub(colnames(genematrix), 4, -10))
pcanames
plot(pc$x[, 1], pc$x[, 2], col = pcagroup, main = "PCA", xlab = "PC1", ylab = "PC2")
summary(pc)
str(pc)
```

## Visualization

```{r}
scores = as.data.frame(pc$x) # extract the scores of the PCA
scores

myColors <- c(rep("lightblue",6),rep("darkblue",6),rep("pink",6),rep("darkred",4))
myColors
pcanames
colScale <- scale_colour_manual(pcagroup,values = myColors)
ggplot(data = scores, aes(x = PC1, y = PC2, label = as.factor(pcanames))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(color = myColors, alpha = 0.8, size = 4) +
  theme_cowplot()
ggplot(data = scores, aes(x = PC3, y = PC4, label = as.factor(pcanames))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(color = myColors, alpha = 0.8, size = 4) +
  theme_cowplot()
ggplot(data = scores, aes(x = PC5, y = PC6, label = as.factor(pcanames))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(color = myColors, alpha = 0.8, size = 4) +
  theme_cowplot()
```

## ggbiplot

```{r}
library(devtools)
install_github("vqv/ggbiplot")
library(ggbiplot)
ggbiplot(pc, scale=0, varname.size = 0, groups = pcagroup, labels = pcanames, ellipse = TRUE, circle = TRUE)
```



## Exporting data for VR

```{r}
head(scores)
VRtable <- as.data.frame(scores)
VRtable$group <- pcagroup
VRtable$individual <- pcanames
VRtable$Id <- rownames(VRtable)
head(VRtable)
write_csv(VRtable, path="PCA.Torpor.forVR.csv")
```

## Making new table 

```{r}
VRtable2 <- VRtable
VRtable2$Temp <- as.factor(str_sub(VRtable2$group, 0, 4))
VRtable2$UV <- as.factor(str_sub(VRtable2$group, 7, 9))
head(VRtable2)
VRtable2 <- VRtable2[,c(25,26,27,1:24)]
write_csv(VRtable2, path="PCA.Torpor.forVR.csv")
```

## Making iris table

```{r}
write_csv(iris, path="iris.csv")
```

## Plotting and extracting rotations for PC22

```{r}
screeplot(pc, npcs = 22, type = "lines")
std_dev <- pc$sdev
pr_var <- std_dev^2
pr_var
prop_varex <- pr_var/sum(pr_var)
prop_varex
plot(prop_varex, xlab = "Principal Component",
             ylab = "Proportion of Variance Explained",
             type = "b")
PC22 <- sort(pc$rotation[,22])
head(PC22)
tail(PC22)
ggplot(data = scores, aes(x = PC1, y = PC22, label = as.factor(pcanames))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(aes(color = pcagroup), alpha = 0.8, size = 4) +
  theme_cowplot()
```

## Generating PC1 rotations for g:Profiler analysis

```{r}
PC1 <- pc$rotation[,1]
head(-sort(PC1))
plot(-sort(PC1))
plot(-sort(PC1)[1:1000])
plot(-sort(PC1)[1:130])
PC1.rotations <- -sort(PC1)[1:130]
write.csv(PC1.rotations, file="../04-Data/Torpor.PCA.PC1.rotations.csv")
```

## Generating Infected vs Uninfected (warm) list for g:Profiler analysis

```{r}
warmPd_posvswarmPd_neg_complete %>%
  filter(padj <= 0.05 & FC >= 2) %>%
  arrange(-FC) %>%
  select(Id) -> upregulated
write_csv(upregulated, path="../04-Data/warmPd_posvswarmPd_neg_upregulated.csv")
```


