### Bradford Assay R tutorial
# Ken Field, Bucknell University

### First enter your data into a data frame 

Concentration <- c(0, 0.2, 0.4, 0.8)
Absorbance <- c(0.05, 0.335, 0.630, 1.050)
Bradford <- data.frame(Concentration, Absorbance)

# Check the contents of the data frame
summary(Bradford)

# show the working directory. This is where files will be saved (and loaded from)
getwd()

# Save the data frame
write.csv(Bradford, file="Bradford.csv")

### Or load it in, if you have already made a spreadsheet
# Note that you will have to save the data in csv format 
# and it needs to be located in the same folder that you are using for the working directory

# load the data from the working directory
Bradford <- read.csv("Bradford.csv")

# or if you saved it as an excel file
library(readxl)
Bradford <- read_excel("Bradford.xlsx")

### We will use the ggplot2 library to make graphs according to the Grammar of Graphics, by Leland Wilkinson
install.packages("ggplot2")
library("ggplot2")

# The basic plotting command ggplot works by specifying the data frame to use, 
# then the independent and dependent variables as aesthetics (aes),
# and finally the type of geometry to use for the plot (in this case a point plot)
ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  geom_point()

# This is not a bad place to start, but we can make the graph less distracting, and more scientifically accurate
# with a few tweaks. First lets make the graph show the full range of possible data down to 0 concentration

ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  geom_point() +
  xlim(0,1) +  ylim(0, 1.2)

# Now lets apply a theme to simplify the appearance of the graphs

ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  geom_point() +
  xlim(0,1) +  ylim(0, 1.2) +
  theme_classic()

## That is nice, but the text is quite small and will be difficult to see in a presentation
# The cowplot package has an even nicer theme.
install.packages("cowplot")
library("cowplot")

ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  geom_point() +
  xlim(0,1) +  ylim(0, 1.2) +
  theme_cowplot()

# We can change the axis labels to be more complete
ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  xlab("Protein (mg/mL)") +
  ylab("Absorbance (at 595 nm)") +
  geom_point() +
  xlim(0,1) +  ylim(0, 1.2) +
  theme_cowplot()

# And finally we can add a regression line to the data (with 95% confidence intervals)
ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  xlab("Protein (mg/mL)") +
  ylab("Absorbance (at 595 nm)") +
  geom_point() +
  xlim(0,1) +  ylim(0, 1.2) +
  theme_cowplot() +
  geom_smooth(method=lm)

## Note that with only 4 data points, the confidence in the linear model not that great 
# and the confidence interval is large. With more datapoints, hopefully the results will be better.
# To plot without the confidence intervals:
ggplot(Bradford) +
  aes(x = Concentration, y = Absorbance) +
  xlab("Protein (mg/mL)") +
  ylab("Absorbance (at 595 nm)") +
  geom_point() +
  xlim(0,1) +  ylim(0, 1.2) +
  theme_cowplot() +
  geom_smooth(method=lm, se = FALSE)

# In R Studio you can now use the Export button right above the graph to save it as a PDF or PNG file

# If you would like to see the equation generated by the regression line you can fit the data separately
fit = lm(Absorbance~Concentration, data=Bradford)
summary(fit)

# This summary includes all of the statistics associated with the linear model fit of the data
# Intercept represents the y-intercept and the slope is shown as Concentration
# The Adjusted R-squared value is also shown